version: '3'

volumes:
  wordpress:
   driver: local
   driver_opts:
     type: none
     device: /home/het-tale/data/wordpress
     o: bind
    

networks:
  inception:
    driver: bridge
  
services:
  nginx:
    container_name: nginx
    build: ./requirements/nginx/.
    image: nginx
    ports:
     - "443:443"
    depends_on:
      - wordpress
    volumes:
      - wordpress:/var/www/html
    networks:
       - inception
    env_file:
      - .env
    restart: always
  wordpress:
    container_name: wordpress
    build: ./requirements/wordpress/.
    image: wordpress
    # depends_on:
    #   mariadb
    volumes:
      - wordpress:/var/www/html
    env_file:
      - .env
    networks:
      - inception
    restart: always